//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export class AuthClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5000";

    }

    login(request: LoginRequest, cancelToken?: CancelToken): Promise<LoginResponse> {
        let url_ = this.baseUrl + "/api/portal/auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: AxiosResponse): Promise<LoginResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = LoginResponse.fromJS(resultData200);
            return Promise.resolve<LoginResponse>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401  = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("A server side error occurred.", status, _responseText, _headers, result401);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<LoginResponse>(null as any);
    }

    refresh(request: RefreshRequest, cancelToken?: CancelToken): Promise<LoginResponse> {
        let url_ = this.baseUrl + "/api/portal/auth/refresh";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRefresh(_response);
        });
    }

    protected processRefresh(response: AxiosResponse): Promise<LoginResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = LoginResponse.fromJS(resultData200);
            return Promise.resolve<LoginResponse>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401  = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("A server side error occurred.", status, _responseText, _headers, result401);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<LoginResponse>(null as any);
    }

    logout(request: RefreshRequest, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/portal/auth/logout";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLogout(_response);
        });
    }

    protected processLogout(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export class TicketClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5000";

    }

    getTickets(status?: TicketStatus | null | undefined, priority?: TicketPriority | null | undefined, categoryId?: number | null | undefined, search?: string | null | undefined, page?: number | undefined, pageSize?: number | undefined, cancelToken?: CancelToken): Promise<PagedResultOfTicketListItemDto> {
        let url_ = this.baseUrl + "/api/portal/tickets?";
        if (status !== undefined && status !== null)
            url_ += "Status=" + encodeURIComponent("" + status) + "&";
        if (priority !== undefined && priority !== null)
            url_ += "Priority=" + encodeURIComponent("" + priority) + "&";
        if (categoryId !== undefined && categoryId !== null)
            url_ += "CategoryId=" + encodeURIComponent("" + categoryId) + "&";
        if (search !== undefined && search !== null)
            url_ += "Search=" + encodeURIComponent("" + search) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "Page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetTickets(_response);
        });
    }

    protected processGetTickets(response: AxiosResponse): Promise<PagedResultOfTicketListItemDto> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = PagedResultOfTicketListItemDto.fromJS(resultData200);
            return Promise.resolve<PagedResultOfTicketListItemDto>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<PagedResultOfTicketListItemDto>(null as any);
    }

    createTicket(request: CreateTicketRequest, cancelToken?: CancelToken): Promise<TicketDetailDto> {
        let url_ = this.baseUrl + "/api/portal/tickets";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreateTicket(_response);
        });
    }

    protected processCreateTicket(response: AxiosResponse): Promise<TicketDetailDto> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 201) {
            const _responseText = response.data;
            let result201: any = null;
            let resultData201  = _responseText;
            result201 = TicketDetailDto.fromJS(resultData201);
            return Promise.resolve<TicketDetailDto>(result201);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TicketDetailDto>(null as any);
    }

    getTicket(id: number, cancelToken?: CancelToken): Promise<TicketDetailDto> {
        let url_ = this.baseUrl + "/api/portal/tickets/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetTicket(_response);
        });
    }

    protected processGetTicket(response: AxiosResponse): Promise<TicketDetailDto> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = TicketDetailDto.fromJS(resultData200);
            return Promise.resolve<TicketDetailDto>(result200);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TicketDetailDto>(null as any);
    }

    updateTicket(id: number, request: UpdateTicketRequest, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/portal/tickets/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdateTicket(_response);
        });
    }

    protected processUpdateTicket(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    updateStatus(id: number, request: UpdateTicketStatusRequest, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/portal/tickets/{id}/status";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PATCH",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdateStatus(_response);
        });
    }

    protected processUpdateStatus(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    assignTicket(id: number, request: AssignTicketRequest, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/portal/tickets/{id}/assign";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PATCH",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAssignTicket(_response);
        });
    }

    protected processAssignTicket(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    toggleCsm(id: number, cancelToken?: CancelToken): Promise<ToggleCsmResponse> {
        let url_ = this.baseUrl + "/api/portal/tickets/{id}/csm";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "PATCH",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processToggleCsm(_response);
        });
    }

    protected processToggleCsm(response: AxiosResponse): Promise<ToggleCsmResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = ToggleCsmResponse.fromJS(resultData200);
            return Promise.resolve<ToggleCsmResponse>(result200);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ToggleCsmResponse>(null as any);
    }

    mergeTicket(id: number, request: MergeTicketRequest, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/portal/tickets/{id}/merge";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processMergeTicket(_response);
        });
    }

    protected processMergeTicket(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status === 409) {
            const _responseText = response.data;
            let result409: any = null;
            let resultData409  = _responseText;
            result409 = ProblemDetails.fromJS(resultData409);
            return throwException("A server side error occurred.", status, _responseText, _headers, result409);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    getMessages(id: number, cancelToken?: CancelToken): Promise<TicketMessageDto[]> {
        let url_ = this.baseUrl + "/api/portal/tickets/{id}/messages";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetMessages(_response);
        });
    }

    protected processGetMessages(response: AxiosResponse): Promise<TicketMessageDto[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TicketMessageDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return Promise.resolve<TicketMessageDto[]>(result200);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TicketMessageDto[]>(null as any);
    }

    addMessage(id: number, request: CreateTicketMessageRequest, cancelToken?: CancelToken): Promise<TicketMessageDto> {
        let url_ = this.baseUrl + "/api/portal/tickets/{id}/messages";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(request);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAddMessage(_response);
        });
    }

    protected processAddMessage(response: AxiosResponse): Promise<TicketMessageDto> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 201) {
            const _responseText = response.data;
            let result201: any = null;
            let resultData201  = _responseText;
            result201 = TicketMessageDto.fromJS(resultData201);
            return Promise.resolve<TicketMessageDto>(result201);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("A server side error occurred.", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TicketMessageDto>(null as any);
    }
}

export class UsersClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "http://localhost:5000";

    }

    getUsers( cancelToken?: CancelToken): Promise<UserSummaryDto[]> {
        let url_ = this.baseUrl + "/api/portal/users";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetUsers(_response);
        });
    }

    protected processGetUsers(response: AxiosResponse): Promise<UserSummaryDto[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(UserSummaryDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return Promise.resolve<UserSummaryDto[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<UserSummaryDto[]>(null as any);
    }
}

export class LoginResponse implements ILoginResponse {
    accessToken?: string;
    refreshToken?: string;
    accessTokenExpires?: Date;
    user?: UserDto;

    constructor(data?: ILoginResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.accessToken = _data["accessToken"];
            this.refreshToken = _data["refreshToken"];
            this.accessTokenExpires = _data["accessTokenExpires"] ? new Date(_data["accessTokenExpires"].toString()) : undefined as any;
            this.user = _data["user"] ? UserDto.fromJS(_data["user"]) : undefined as any;
        }
    }

    static fromJS(data: any): LoginResponse {
        data = typeof data === 'object' ? data : {};
        let result = new LoginResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["accessToken"] = this.accessToken;
        data["refreshToken"] = this.refreshToken;
        data["accessTokenExpires"] = this.accessTokenExpires ? this.accessTokenExpires.toISOString() : undefined as any;
        data["user"] = this.user ? this.user.toJSON() : undefined as any;
        return data;
    }
}

export interface ILoginResponse {
    accessToken?: string;
    refreshToken?: string;
    accessTokenExpires?: Date;
    user?: UserDto;
}

export class UserDto implements IUserDto {
    id?: number;
    email?: string;
    fullName?: string;
    role?: string;

    constructor(data?: IUserDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.email = _data["email"];
            this.fullName = _data["fullName"];
            this.role = _data["role"];
        }
    }

    static fromJS(data: any): UserDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["email"] = this.email;
        data["fullName"] = this.fullName;
        data["role"] = this.role;
        return data;
    }
}

export interface IUserDto {
    id?: number;
    email?: string;
    fullName?: string;
    role?: string;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class LoginRequest implements ILoginRequest {
    email?: string;
    password?: string;
    rememberMe?: boolean;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.email = _data["email"];
            this.password = _data["password"];
            this.rememberMe = _data["rememberMe"];
        }
    }

    static fromJS(data: any): LoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email;
        data["password"] = this.password;
        data["rememberMe"] = this.rememberMe;
        return data;
    }
}

export interface ILoginRequest {
    email?: string;
    password?: string;
    rememberMe?: boolean;
}

export class RefreshRequest implements IRefreshRequest {
    refreshToken?: string;

    constructor(data?: IRefreshRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.refreshToken = _data["refreshToken"];
        }
    }

    static fromJS(data: any): RefreshRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RefreshRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["refreshToken"] = this.refreshToken;
        return data;
    }
}

export interface IRefreshRequest {
    refreshToken?: string;
}

export class PagedResultOfTicketListItemDto implements IPagedResultOfTicketListItemDto {
    items?: TicketListItemDto[];
    page?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;

    constructor(data?: IPagedResultOfTicketListItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(TicketListItemDto.fromJS(item));
            }
            this.page = _data["page"];
            this.pageSize = _data["pageSize"];
            this.totalCount = _data["totalCount"];
            this.totalPages = _data["totalPages"];
        }
    }

    static fromJS(data: any): PagedResultOfTicketListItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new PagedResultOfTicketListItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["page"] = this.page;
        data["pageSize"] = this.pageSize;
        data["totalCount"] = this.totalCount;
        data["totalPages"] = this.totalPages;
        return data;
    }
}

export interface IPagedResultOfTicketListItemDto {
    items?: TicketListItemDto[];
    page?: number;
    pageSize?: number;
    totalCount?: number;
    totalPages?: number;
}

export class TicketListItemDto implements ITicketListItemDto {
    id?: number;
    subject?: string;
    status?: TicketStatus;
    priority?: TicketPriority;
    categoryId?: number | undefined;
    categoryName?: string | undefined;
    assignedToId?: number | undefined;
    assignedToName?: string | undefined;
    requesterEmail?: string;
    requesterName?: string;
    isCsmFlagged?: boolean;
    isMerged?: boolean;
    slaDueAt?: Date | undefined;
    slaBreach?: boolean;
    createdAt?: Date;
    updatedAt?: Date;

    constructor(data?: ITicketListItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.subject = _data["subject"];
            this.status = _data["status"];
            this.priority = _data["priority"];
            this.categoryId = _data["categoryId"];
            this.categoryName = _data["categoryName"];
            this.assignedToId = _data["assignedToId"];
            this.assignedToName = _data["assignedToName"];
            this.requesterEmail = _data["requesterEmail"];
            this.requesterName = _data["requesterName"];
            this.isCsmFlagged = _data["isCsmFlagged"];
            this.isMerged = _data["isMerged"];
            this.slaDueAt = _data["slaDueAt"] ? new Date(_data["slaDueAt"].toString()) : undefined as any;
            this.slaBreach = _data["slaBreach"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): TicketListItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new TicketListItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["subject"] = this.subject;
        data["status"] = this.status;
        data["priority"] = this.priority;
        data["categoryId"] = this.categoryId;
        data["categoryName"] = this.categoryName;
        data["assignedToId"] = this.assignedToId;
        data["assignedToName"] = this.assignedToName;
        data["requesterEmail"] = this.requesterEmail;
        data["requesterName"] = this.requesterName;
        data["isCsmFlagged"] = this.isCsmFlagged;
        data["isMerged"] = this.isMerged;
        data["slaDueAt"] = this.slaDueAt ? this.slaDueAt.toISOString() : undefined as any;
        data["slaBreach"] = this.slaBreach;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        return data;
    }
}

export interface ITicketListItemDto {
    id?: number;
    subject?: string;
    status?: TicketStatus;
    priority?: TicketPriority;
    categoryId?: number | undefined;
    categoryName?: string | undefined;
    assignedToId?: number | undefined;
    assignedToName?: string | undefined;
    requesterEmail?: string;
    requesterName?: string;
    isCsmFlagged?: boolean;
    isMerged?: boolean;
    slaDueAt?: Date | undefined;
    slaBreach?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

export enum TicketStatus {
    New = "New",
    Open = "Open",
    Pending = "Pending",
    Resolved = "Resolved",
    Closed = "Closed",
}

export enum TicketPriority {
    Low = "Low",
    Medium = "Medium",
    High = "High",
    Urgent = "Urgent",
}

export class TicketDetailDto implements ITicketDetailDto {
    id?: number;
    subject?: string;
    body?: string;
    status?: TicketStatus;
    priority?: TicketPriority;
    categoryId?: number | undefined;
    categoryName?: string | undefined;
    assignedToId?: number | undefined;
    assignedToName?: string | undefined;
    createdById?: number | undefined;
    createdByName?: string | undefined;
    requesterEmail?: string;
    requesterName?: string;
    source?: TicketSource;
    isCsmFlagged?: boolean;
    isMerged?: boolean;
    mergedIntoTicketId?: number | undefined;
    slaDueAt?: Date | undefined;
    slaBreach?: boolean;
    createdAt?: Date;
    updatedAt?: Date;

    constructor(data?: ITicketDetailDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.subject = _data["subject"];
            this.body = _data["body"];
            this.status = _data["status"];
            this.priority = _data["priority"];
            this.categoryId = _data["categoryId"];
            this.categoryName = _data["categoryName"];
            this.assignedToId = _data["assignedToId"];
            this.assignedToName = _data["assignedToName"];
            this.createdById = _data["createdById"];
            this.createdByName = _data["createdByName"];
            this.requesterEmail = _data["requesterEmail"];
            this.requesterName = _data["requesterName"];
            this.source = _data["source"];
            this.isCsmFlagged = _data["isCsmFlagged"];
            this.isMerged = _data["isMerged"];
            this.mergedIntoTicketId = _data["mergedIntoTicketId"];
            this.slaDueAt = _data["slaDueAt"] ? new Date(_data["slaDueAt"].toString()) : undefined as any;
            this.slaBreach = _data["slaBreach"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): TicketDetailDto {
        data = typeof data === 'object' ? data : {};
        let result = new TicketDetailDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["subject"] = this.subject;
        data["body"] = this.body;
        data["status"] = this.status;
        data["priority"] = this.priority;
        data["categoryId"] = this.categoryId;
        data["categoryName"] = this.categoryName;
        data["assignedToId"] = this.assignedToId;
        data["assignedToName"] = this.assignedToName;
        data["createdById"] = this.createdById;
        data["createdByName"] = this.createdByName;
        data["requesterEmail"] = this.requesterEmail;
        data["requesterName"] = this.requesterName;
        data["source"] = this.source;
        data["isCsmFlagged"] = this.isCsmFlagged;
        data["isMerged"] = this.isMerged;
        data["mergedIntoTicketId"] = this.mergedIntoTicketId;
        data["slaDueAt"] = this.slaDueAt ? this.slaDueAt.toISOString() : undefined as any;
        data["slaBreach"] = this.slaBreach;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        return data;
    }
}

export interface ITicketDetailDto {
    id?: number;
    subject?: string;
    body?: string;
    status?: TicketStatus;
    priority?: TicketPriority;
    categoryId?: number | undefined;
    categoryName?: string | undefined;
    assignedToId?: number | undefined;
    assignedToName?: string | undefined;
    createdById?: number | undefined;
    createdByName?: string | undefined;
    requesterEmail?: string;
    requesterName?: string;
    source?: TicketSource;
    isCsmFlagged?: boolean;
    isMerged?: boolean;
    mergedIntoTicketId?: number | undefined;
    slaDueAt?: Date | undefined;
    slaBreach?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

export enum TicketSource {
    Email = "Email",
    Portal = "Portal",
    Manual = "Manual",
}

export class CreateTicketRequest implements ICreateTicketRequest {
    subject?: string;
    body?: string;
    priority?: TicketPriority;
    categoryId?: number | undefined;
    requesterEmail?: string;
    requesterName?: string;
    assignedToId?: number | undefined;

    constructor(data?: ICreateTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.subject = _data["subject"];
            this.body = _data["body"];
            this.priority = _data["priority"];
            this.categoryId = _data["categoryId"];
            this.requesterEmail = _data["requesterEmail"];
            this.requesterName = _data["requesterName"];
            this.assignedToId = _data["assignedToId"];
        }
    }

    static fromJS(data: any): CreateTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["subject"] = this.subject;
        data["body"] = this.body;
        data["priority"] = this.priority;
        data["categoryId"] = this.categoryId;
        data["requesterEmail"] = this.requesterEmail;
        data["requesterName"] = this.requesterName;
        data["assignedToId"] = this.assignedToId;
        return data;
    }
}

export interface ICreateTicketRequest {
    subject?: string;
    body?: string;
    priority?: TicketPriority;
    categoryId?: number | undefined;
    requesterEmail?: string;
    requesterName?: string;
    assignedToId?: number | undefined;
}

export class UpdateTicketRequest implements IUpdateTicketRequest {
    subject?: string;
    body?: string;
    priority?: TicketPriority;
    categoryId?: number | undefined;
    requesterEmail?: string;
    requesterName?: string;

    constructor(data?: IUpdateTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.subject = _data["subject"];
            this.body = _data["body"];
            this.priority = _data["priority"];
            this.categoryId = _data["categoryId"];
            this.requesterEmail = _data["requesterEmail"];
            this.requesterName = _data["requesterName"];
        }
    }

    static fromJS(data: any): UpdateTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["subject"] = this.subject;
        data["body"] = this.body;
        data["priority"] = this.priority;
        data["categoryId"] = this.categoryId;
        data["requesterEmail"] = this.requesterEmail;
        data["requesterName"] = this.requesterName;
        return data;
    }
}

export interface IUpdateTicketRequest {
    subject?: string;
    body?: string;
    priority?: TicketPriority;
    categoryId?: number | undefined;
    requesterEmail?: string;
    requesterName?: string;
}

export class UpdateTicketStatusRequest implements IUpdateTicketStatusRequest {
    status?: TicketStatus;

    constructor(data?: IUpdateTicketStatusRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.status = _data["status"];
        }
    }

    static fromJS(data: any): UpdateTicketStatusRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTicketStatusRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["status"] = this.status;
        return data;
    }
}

export interface IUpdateTicketStatusRequest {
    status?: TicketStatus;
}

export class AssignTicketRequest implements IAssignTicketRequest {
    assignedToId?: number | undefined;

    constructor(data?: IAssignTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.assignedToId = _data["assignedToId"];
        }
    }

    static fromJS(data: any): AssignTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AssignTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["assignedToId"] = this.assignedToId;
        return data;
    }
}

export interface IAssignTicketRequest {
    assignedToId?: number | undefined;
}

export class ToggleCsmResponse implements IToggleCsmResponse {
    isCsmFlagged?: boolean;

    constructor(data?: IToggleCsmResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isCsmFlagged = _data["isCsmFlagged"];
        }
    }

    static fromJS(data: any): ToggleCsmResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ToggleCsmResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isCsmFlagged"] = this.isCsmFlagged;
        return data;
    }
}

export interface IToggleCsmResponse {
    isCsmFlagged?: boolean;
}

export class MergeTicketRequest implements IMergeTicketRequest {
    targetTicketId?: number;

    constructor(data?: IMergeTicketRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.targetTicketId = _data["targetTicketId"];
        }
    }

    static fromJS(data: any): MergeTicketRequest {
        data = typeof data === 'object' ? data : {};
        let result = new MergeTicketRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["targetTicketId"] = this.targetTicketId;
        return data;
    }
}

export interface IMergeTicketRequest {
    targetTicketId?: number;
}

export class TicketMessageDto implements ITicketMessageDto {
    id?: number;
    ticketId?: number;
    senderUserId?: number | undefined;
    senderUserName?: string | undefined;
    senderEmail?: string | undefined;
    body?: string;
    isInternalNote?: boolean;
    direction?: MessageDirection;
    createdAt?: Date;

    constructor(data?: ITicketMessageDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.ticketId = _data["ticketId"];
            this.senderUserId = _data["senderUserId"];
            this.senderUserName = _data["senderUserName"];
            this.senderEmail = _data["senderEmail"];
            this.body = _data["body"];
            this.isInternalNote = _data["isInternalNote"];
            this.direction = _data["direction"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): TicketMessageDto {
        data = typeof data === 'object' ? data : {};
        let result = new TicketMessageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["ticketId"] = this.ticketId;
        data["senderUserId"] = this.senderUserId;
        data["senderUserName"] = this.senderUserName;
        data["senderEmail"] = this.senderEmail;
        data["body"] = this.body;
        data["isInternalNote"] = this.isInternalNote;
        data["direction"] = this.direction;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        return data;
    }
}

export interface ITicketMessageDto {
    id?: number;
    ticketId?: number;
    senderUserId?: number | undefined;
    senderUserName?: string | undefined;
    senderEmail?: string | undefined;
    body?: string;
    isInternalNote?: boolean;
    direction?: MessageDirection;
    createdAt?: Date;
}

export enum MessageDirection {
    Inbound = "Inbound",
    Outbound = "Outbound",
}

export class CreateTicketMessageRequest implements ICreateTicketMessageRequest {
    body?: string;
    isInternalNote?: boolean;

    constructor(data?: ICreateTicketMessageRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.body = _data["body"];
            this.isInternalNote = _data["isInternalNote"];
        }
    }

    static fromJS(data: any): CreateTicketMessageRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTicketMessageRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["body"] = this.body;
        data["isInternalNote"] = this.isInternalNote;
        return data;
    }
}

export interface ICreateTicketMessageRequest {
    body?: string;
    isInternalNote?: boolean;
}

export class UserSummaryDto implements IUserSummaryDto {
    id?: number;
    fullName?: string;
    email?: string;
    role?: string;

    constructor(data?: IUserSummaryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.fullName = _data["fullName"];
            this.email = _data["email"];
            this.role = _data["role"];
        }
    }

    static fromJS(data: any): UserSummaryDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserSummaryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["fullName"] = this.fullName;
        data["email"] = this.email;
        data["role"] = this.role;
        return data;
    }
}

export interface IUserSummaryDto {
    id?: number;
    fullName?: string;
    email?: string;
    role?: string;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}